name: Deploy to Salesforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Salesforce CLI with NPM
        run: |
          npm install @salesforce/cli --global

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > sfdx_auth_url.txt sfdx auth:sfdxurl:store -f sfdx_auth_url.txt

      - name: Deploy to Salesforce
        run: |
          sf project deploy start --target-org vscodeOrg --wait 30