public class example15may
{
   public void add( integer a, integer b)
   {
       system.debug ('executing method with two para');
       integer addition = a+b;
       system.debug ('add is '+addition);
   }
    public void add( integer a, integer b, integer c)
    {
        system.debug ('executing method with 3 para');
          integer addition =a+b+c;
           system.debug ('add is '+addition);  
    }
     public void add( string a, string b)
   {
       system.debug ('executing method with two para');
       string addition = a+b;
       system.debug ('add is '+addition);
   }
    
}